### ISSUE TITLE
Some 0.5 milestones

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#343]
- [ ] Seed the tractography on the white matter-grey matter boundary
- [ ] Add dki mk scalar
- [ ] Add support for MSMT
- [ ] Add support for Particle Filtering Tractography (#335)

**Comment by arokem** [comment]
Closing in favor of individual issues and PR.
